### ISSUE TITLE
ServiceActivator should support multiple channels

### ISSUE THREAD

**Issue by ngbalk** [spring-cloud-stream-app-starters/router#2]
https://github.com/spring-cloud-stream-app-starters/router/blob/c888df571fbda3f529d712a0f520bda24c09f794/spring-cloud-starter-stream-sink-router/src/main/java/org/springframework/cloud/stream/app/router/sink/RouterSinkConfiguration.java#L51

Imagine we had multiple channels, but we wanted to apply similar routing logic to each channel - could ServiceActivator support binding the router to multiple channels to support this?

**Comment by artembilan** [comment]
Closed in favor of https://github.com/spring-projects/spring-integration/issues/2505

Also in Spring Cloud Data Flow streams you can configure a `bridge` processor to fan-in from different destination to a single input of some mincoservice.
